import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { CartProvider } from "./contex/cartcontex";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pay N Deliver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <CartProvider>
        {/* <Header/> */}
        {children}
        <Footer/>
        </CartProvider>
              </body>
    </html>
  );
}
